// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dckzklqbibmqaspdqknf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRja3prbHFiaWJtcWFzcGRxa25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Njc5MjQsImV4cCI6MjA2NjQ0MzkyNH0.vvrH4FdvY384XLTWXtTKz1nxaX5ZdJr4F31Zhs-AMnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);